ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
ACTIONS_TO_NUMBER = {"UP": 0, "RIGHT": 1, "DOWN": 2, "LEFT": 3, "WAIT": 4, "BOMB": 5}

INPUT_SHAPE = (5, 17, 17)

BATCH_SIZE = 32
TRANSITION_HISTORY_SIZE = 100
LEARNING_RATE = 0.00005
NUMBER_EPOCHS = 100
EPSILON = .1
